// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkMyBike.Models;

namespace ParkMyBike.Migrations
{
    [DbContext(typeof(BikeRackContext))]
    [Migration("20200304023739_initialDb")]
    partial class initialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkMyBike.Models.Entities.BikeRack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRacks")
                        .HasColumnType("int");

                    b.Property<int>("RackType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BikeRacks");
                });

            modelBuilder.Entity("ParkMyBike.Models.Entities.BikeRack", b =>
                {
                    b.OwnsOne("ParkMyBike.Models.Entities.Position", "Position", b1 =>
                        {
                            b1.Property<int>("BikeRackId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("BikeRackId");

                            b1.ToTable("BikeRacks");

                            b1.WithOwner()
                                .HasForeignKey("BikeRackId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
